basePath: /
host: localhost:8080
info:
  contact:
    email: team@boletia
    name: API Support
    url: boletia
  description: This project query to currency api and change the values.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Currencies
  version: "1.0"
paths: {}
swagger: "2.0"
